title: Oneder1's Blog
url: "https://oneder1.github.io/"
description: "Trying to be a good software engineer"

exclude: [Gemfile, Gemfile.lock, README.md]
markdown: kramdown

author: "Oneder1"
disqus_shortname: oneder1
google_analytics: UA-42209870-1

plugins:
  # https://help.github.com/articles/atom-rss-feeds-for-github-pages/
  - jekyll-gist
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: :compressed
